INTERIOR_BTREE_PAGE_HEADER_SIZE = 12
LEAF_BTREE_PAGE_HEADER_SIZE = 8
DATABASE_FILE_HEADER_SIZE = 100

INTERIOR_INDEX_BTREE_PAGE_FLAG = 2
INTERIROR_TABLE_BTREE_PAGE_FLAG = 5
LEAF_INTERIOR_DISTINGUISH_NUM = 10
LEAF_INDEX_BTREE_PAGE_FLAG = 10
LEAF_TABLE_BTREE_PAGE_FLAG = 13

BTREE_NUM_CELLS_OFFSET = 3
BTREE_START_CELLCONTENT_AREA_OFFSET = 5

CELL_POINTER_SIZE = 2 # 2 bytes for each pointer

PAGE_SIZE_4K = 4096
PAGE_SIZE_16K = 16384
POINTER_SIZE = 4
RESERVED_PER_PAGE = 0

DB_PATH1="C:\\Users\\Max You\\Desktop\\COURSES\\CSC443\\db1.db"
DB_PATH2="C:\\Users\\Max You\\Desktop\\COURSES\\CSC443\\db2.db"
DB_PATH3="C:\\Users\\Max You\\Desktop\\COURSES\\CSC443\\db3.db"
DB_PATH4="C:\\Users\\Max You\\Desktop\\COURSES\\CSC443\\db4.db"
#DB_PATH = "C:\\Users\\MaxYou\\Desktop\\CSC443\\dbtest.db"

# the rest are the query conditions
LAST_NAME = "Rowe" # should be 28 results
EMP_ID = 181162
#EMP_ID =171800
# not inclusive
EMP_ID_RANGE = (171800, 171899)

EMP_ID_INDEX = 0
FIRST_NAME_INDEX = 2
MIDDLE_NAME_INDEX = 3
LAST_NAME_INDEX = 4